### ISSUE TITLE
issue-01

### ISSUE THREAD

**Issue by szilardto** [szilardto/issue_tracker_test#1]

**Comment by szilardto** [comment]
what is this?

**Comment by szilardto** [comment]
closed issue

**Comment by megancook** [comment]
<img width="128" alt="screen shot 2016-06-10 at 9 37 59 am" src="https://cloud.githubusercontent.com/assets/5885301/16185574/2e2279e6-3708-11e6-83da-8ea5a9eb8a27.png">
